FROM node:lts-alpine

ENV NODE_ENV=development

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN chown -R node /usr/src/app

USER node

COPY . .

EXPOSE 3000

CMD ["yarn", "start:dev"]
